version: '3.6'
services:
  db:
    image: 'postgres:11-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    #volumes:
    #  - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    depends_on:
      - db
    # environment:
      # MIX_ENV: dev
    # env_file:
      # - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
# volumes:
#   pgdata:
